# Generated by Django 2.2.5 on 2019-10-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191011_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ruc', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='company_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.Company'),
            preserve_default=False,
        ),
    ]
