# Generated by Django 2.2.4 on 2019-10-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20191017_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='https://source.unsplash.com/random/1', max_length=100),
        ),
    ]
