# Generated by Django 2.2.4 on 2019-10-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191017_2114'),
        ('product', '0003_auto_20191011_1546'),
    ]

    operations = [
    ]
