# Generated by Django 2.2.5 on 2019-11-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_merge_20191029_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company_id',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
